### ISSUE TITLE
和 IDEA 2018.3 不兼容

### ISSUE THREAD

**Issue by xtuer** [mustfun/mybatis-plus#14]
在 IDEA 2018.3 里不能运行

**Comment by wellxion** [comment]
這邊2018.3測試也不能用
![image](https://user-images.githubusercontent.com/5474710/49133233-3513f600-f31a-11e8-8a06-8965116638a4.png)

**Comment by yao00jun** [comment]
我也是 IDEA 2018.3 里不能运行
