### ISSUE TITLE
新版数据库连接失败

### ISSUE THREAD

**Issue by LloydLai** [mustfun/mybatis-plus#33]
![image](https://user-images.githubusercontent.com/48792675/57567465-435b5780-740c-11e9-9c30-c3ae1c12df43.png)
s最新的插件DBUtil类中数据库连接驱动还是com.mysql.jdbc.Driver，没有更新成com.mysql.cj.jdbc.Driver，导致数据库连接失败

**Comment by mustfun** [comment]
最新版已提交，预计审核1-2天，感谢建议
