### ISSUE TITLE
请问楼主,在哪里可以学习插件开发.收费那个插件越来越坑了.居然还想做成每年300块订阅,估计走不了多久了.

### ISSUE THREAD

**Issue by yangzhaoyunfei** [mustfun/mybatis-plus#36]

**Comment by chuntungho** [comment]
参考jetbrain官网教程，marketplace找不到一个适合CE版的图形工具，干脆自己弄了个mybatis builder，初版大概用了一周的业余时间

**Comment by mustfun** [comment]
@yangzhaoyunfei   不好意思，回复晚了，官方sdk在这里： http://www.jetbrains.org/intellij/sdk/docs/welcome.html
图形工具 IDEA本身就支持一些简单的拖拽，够用了，其它就是java基础了，加油
